export const SITE = {
  title: 'SONEX - The DeFi Quickening on Soneium',
  description:
    'SONEX is your gateway to the Soneium ecosystem, transforming decentralized finance with a seamless, all-in-one DeFi hub tailored for retail users. Say goodbye to reliance on centralized platforms—experience the power of true decentralization with SONEX.',
}

export const OPEN_GRAPH = {
  type: 'website',
  url: 'https://sonex.so',
  title: 'The DeFi Quickening on Soneium',
  description:
    'SONEX is your gateway to the Soneium ecosystem, transforming decentralized finance with a seamless, all-in-one DeFi hub tailored for retail users. Say goodbye to reliance on centralized platforms—experience the power of true decentralization with SONEX.',
  siteName: 'SONEX',
  images: [
    {
      url: 'https://raw.githubusercontent.com/spherex-dex/sonex-swap-tokens/main/sonex-og.png',
    },
  ],
}

export const TWITTER = {
  card: 'summary_large_image',
  site: '@sonex_so',
  creator: '@sonex_so',
  images:
    'https://raw.githubusercontent.com/spherex-dex/sonex-swap-tokens/main/sonex-og.png',
}

export const KEY_WORDS_EN = {
  home: [
    'SoneX',
    'web3',
    'how to buy',
    'SONEX, Blockchain',
    'Soneium blockchain',
    'SONY',
    'SONY Blockchain',
    'DeFi on Soneium',
    'Astar',
    'Astar Network',
    'Sota Watanabe',
    'SONY Layer2',
    'SoneX DEX',
    'SONY DEX',
    'SONY Swap',
    'decentralized exchange',
    'crypto swap platform',
    'DeFi trading',
    'secure crypto swaps',
    'DeFi on SONY Blockchain',
    'SoneX crypto trading',
    'blockchain swap DEX',
    'seamless crypto swaps',
    'DeFi ecosystem on Soneium',
    'decentralized finance swaps',
    'swap tokens on SoneX',
    'SoneX swap DEX',
    'secure DeFi trading',
    'SoneX trading platform',
  ],
  swap: [
    'SoneX',
    'web3',
    'how to buy',
    'SONEX',
    'Blockchain',
    'Soneium blockchain',
    'SONY',
    'SONY Blockchain',
    'DeFi on Soneium',
    'Astar',
    'Astar Network',
    'Sota Watanabe',
    'SONY Layer2',
    'SoneX DEX',
    'SONY DEX',
    'SONY Swap',
    'decentralized exchange',
    'crypto swap platform',
    'DeFi trading',
    'secure crypto swaps',
    'DeFi on SONY Blockchain',
    'SoneX crypto trading',
    'blockchain swap DEX',
    'seamless crypto swaps',
    'DeFi ecosystem on Soneium',
    'decentralized finance swaps',
    'swap tokens on SoneX',
    'SoneX swap DEX',
    'secure DeFi trading',
    'SoneX trading platform',
  ],
  explore: [
    'explore',
    'pools',
    'transactions',
    'Astar',
    'Astar Network',
    'Sota Watanabe',
    'SONY Layer2',
    'crypto swap platform,',
    'SoneX crypto trading',
    'blockchain swap DEX',
    'seamless crypto swaps',
    'DeFi ecosystem on Soneium',
    'decentralized finance swaps',
    'swap tokens on SoneX',
    'SoneX swap DEX',
    'secure DeFi trading',
    'SoneX trading platform',
    'Soneium blockchain, SONY',
    'SONY Blockchain',
    'DeFi on Soneium',
  ],
  pool: [
    'pool',
    'pools',
    'SoneX',
    'web3',
    'how to buy',
    'SONEX',
    'Blockchain',
    'Soneium blockchain',
    'SONY',
    'SONY Blockchain',
    'DeFi on Soneium',
    'Astar',
    'Astar Network',
    'Sota Watanabe',
    'SONY Layer2',
    'SoneX DEX',
    'SONY DEX',
    'SONY Swap',
    'decentralized exchange',
    'crypto swap platform',
    'DeFi trading',
    'secure crypto swaps',
    'DeFi on SONY Blockchain',
    'SoneX crypto trading',
    'blockchain swap DEX',
    'seamless crypto swaps',
    'DeFi ecosystem on Soneium',
    'decentralized finance swaps',
    'swap tokens on SoneX',
    'SoneX swap DEX',
    'secure DeFi trading',
    'SoneX trading platform',
  ],
  faucet: [
    'faucet',
    'SoneX',
    'web3',
    'how to buy',
    'SONEX',
    'Blockchain',
    'Soneium blockchain',
    'SONY',
    'SONY Blockchain',
    'DeFi on Soneium',
    'Astar',
    'Astar Network',
    'Sota Watanabe',
    'SONY Layer2',
    'SoneX DEX',
    'SONY DEX',
    'SONY Swap',
    'decentralized exchange',
    'crypto swap platform',
    'DeFi trading',
    'secure crypto swaps',
    'DeFi on SONY Blockchain',
    'SoneX crypto trading',
    'blockchain swap DEX',
    'seamless crypto swaps',
    'DeFi ecosystem on Soneium',
    'decentralized finance swaps',
    'swap tokens on SoneX',
    'SoneX swap DEX',
    'secure DeFi trading',
    'SoneX trading platform',
  ],
}

export const KEY_WORDS_ZH = {
  home: [
    '赚币',
    '积分',
    '价格预测',
    '索尼公链',
    '如何购买',
    '区块链',
    'Astar 网络',
    '平井一夫',
    '二层网络',
    '去中心化交易所 ',
    '兑换平台 ',
    '去中心化交易所',
    '加密货币兑换平台',
    'DeFi 交易 ',
    '安全加密货币兑换 ',
    '区块链上的 DeFi',
    'SoneX 加密货币交易',
    '区块链兑换去中心化交易所',
    '无缝加密货币兑换',
    'DeFi 生态系统',
    '去中心化金融兑换',
    '兑换代币',
    '兑换去中心化交易所',
    '安全 DeFi 交易',
    'SoneX 交易平台 ',
    'Soneium 区块链',
    '索尼',
    '索尼区块链',
    '索尼链',
  ],
  swap: [
    '价格预测',
    '索尼公链',
    '如何购买',
    '平井一夫',
    '二层网络',
    'DeFi 交易',
    '安全加密货币兑换 ',
    '区块链上的 DeFi',
    '去中心化金融兑换',
    '兑换代币',
    '兑换去中心化交易所',
    'SoneX 交易平台',
    'Soneium 区块链',
    '索尼',
    '索尼区块链',
    '索尼链',
  ],
  explore: [
    '索尼公链Astar 网络',
    '平井一夫',
    '二层网络',
    'DeFi 交易 ',
    '安全加密货币兑换',
    '区块链上的 DeFi',
    'SoneX 加密货币交易',
    '区块链兑换去中心化交易所',
    '无缝加密货币兑换',
    'DeFi 生态系统',
    '去中心化金融兑换',
    '兑换代币',
    '兑换去中心化交易所',
    '安全 DeFi 交易',
    'SoneX 交易平台 ',
    'Soneium 区块链',
    '索尼',
    '索尼区块链',
    '索尼链',
  ],
  pool: [
    '赚币',
    '积分',
    '价格预测',
    '索尼公链',
    '如何购买',
    '区块链',
    'Astar 网络',
    '平井一夫',
    '二层网络',
    '去中心化交易所',
    '兑换平台',
    '去中心化交易所',
    '加密货币兑换平台',
    'DeFi 交易',
    '安全加密货币兑换 ',
    '区块链上的 DeFi',
    'SoneX 加密货币交易',
    '区块链兑换去中心化交易所',
    '无缝加密货币兑换',
    'DeFi 生态系统',
    '去中心化金融兑换',
    '兑换代币',
    '兑换去中心化交易所',
    '安全 DeFi 交易',
    'SoneX 交易平台',
    'Soneium 区块链',
    '索尼',
    '索尼区块链',
    '索尼链',
  ],
  faucet: [
    '测试网',
    '水龙头',
    'opbnb',
    '赚币',
    '积分',
    '价格预测',
    '索尼公链',
    '如何购买',
    '区块链',
    'Astar 网络',
    '平井一夫',
    '二层网络',
    '去中心化交易所 ',
    '兑换平台 ',
    '去中心化交易所',
    '加密货币兑换平台',
    'DeFi 交易',
    '安全加密货币兑换 ',
    '区块链上的 DeFi',
    'SoneX 加密货币交易',
    '区块链兑换去中心化交易所',
    '无缝加密货币兑换',
    'DeFi 生态系统',
    '去中心化金融兑换',
    '兑换代币',
    '兑换去中心化交易所',
    '安全 DeFi 交易',
    'SoneX 交易平台',
    'Soneium 区块链',
    '索尼',
    '索尼区块链',
    '索尼链',
  ],
}

export const SEO_LINKS = {
  home: [
    {
      name: 'Development of Blockchain "Soneium™"',
      url: 'https://www.sony.com/en/SonyInfo/News/Press/202408/24-029E/',
    },
    {
      name: 'Soneium',
      url: 'https://www.coingecko.com/learn/what-is-soneium-sony-crypto#:~:text=Sony%20launched%20Soneium%2C%20a%20Layer,Optimism%2C%20joining%20the%20Superchain%20ecosystem.',
    },
    {
      name: 'Soneium token airdrop guide',
      url: 'https://boxmining.com/soneium-token-airdrop-guide/',
    },
    {
      name: 'The Sony Blockchain',
      url: 'https://www.youtube.com/watch?v=okEk7iKQccU',
    },
    {
      name: 'Why is Sony Launching Its Own Blockchain Platform?',
      url: 'https://technologymagazine.com/articles/why-is-sony-launching-its-own-blockchain-platform',
    },
    {
      name: 'Sony Blockchain Technology',
      url: 'https://www.japantimes.co.jp/business/2024/09/18/companies/sony-blockchain-technology/',
    },
    {
      name: 'Astar Network',
      url: 'https://astar.network/',
    },
    {
      name: 'Astar',
      url: 'https://coinmarketcap.com/currencies/astar/',
    },
    {
      name: 'Astar Coins',
      url: 'https://www.coingecko.com/en/coins/astar',
    },
  ],
  swap: [
    {
      name: 'Development of Blockchain "Soneium™"',
      url: 'https://www.sony.com/en/SonyInfo/News/Press/202408/24-029E/',
    },
    {
      name: 'Soneium',
      url: 'https://www.coingecko.com/learn/what-is-soneium-sony-crypto#:~:text=Sony%20launched%20Soneium%2C%20a%20Layer,Optimism%2C%20joining%20the%20Superchain%20ecosystem.',
    },
    {
      name: 'Soneium token airdrop guide',
      url: 'https://boxmining.com/soneium-token-airdrop-guide/',
    },
    {
      name: 'The Sony Blockchain',
      url: 'https://www.youtube.com/watch?v=okEk7iKQccU',
    },
    {
      name: 'Why is Sony Launching Its Own Blockchain Platform?',
      url: 'https://technologymagazine.com/articles/why-is-sony-launching-its-own-blockchain-platform',
    },
    {
      name: 'Sony Blockchain Technology',
      url: 'https://www.japantimes.co.jp/business/2024/09/18/companies/sony-blockchain-technology/',
    },
    {
      name: 'Astar Network',
      url: 'https://astar.network/',
    },
    {
      name: 'Astar',
      url: 'https://coinmarketcap.com/currencies/astar/',
    },
    {
      name: 'Astar Coins',
      url: 'https://www.coingecko.com/en/coins/astar',
    },
  ],
  explore: [
    {
      name: 'Development of Blockchain "Soneium™"',
      url: 'https://www.sony.com/en/SonyInfo/News/Press/202408/24-029E/',
    },
    {
      name: 'Soneium',
      url: 'https://www.coingecko.com/learn/what-is-soneium-sony-crypto#:~:text=Sony%20launched%20Soneium%2C%20a%20Layer,Optimism%2C%20joining%20the%20Superchain%20ecosystem.',
    },
    {
      name: 'Soneium token airdrop guide',
      url: 'https://boxmining.com/soneium-token-airdrop-guide/',
    },
    {
      name: 'The Sony Blockchain',
      url: 'https://www.youtube.com/watch?v=okEk7iKQccU',
    },
    {
      name: 'Why is Sony Launching Its Own Blockchain Platform?',
      url: 'https://technologymagazine.com/articles/why-is-sony-launching-its-own-blockchain-platform',
    },
  ],
  pool: [
    {
      name: 'Development of Blockchain "Soneium™"',
      url: 'https://www.sony.com/en/SonyInfo/News/Press/202408/24-029E/',
    },
    {
      name: 'Soneium',
      url: 'https://www.coingecko.com/learn/what-is-soneium-sony-crypto#:~:text=Sony%20launched%20Soneium%2C%20a%20Layer,Optimism%2C%20joining%20the%20Superchain%20ecosystem.',
    },
    {
      name: 'Soneium token airdrop guide',
      url: 'https://boxmining.com/soneium-token-airdrop-guide/',
    },
    {
      name: 'The Sony Blockchain',
      url: 'https://www.youtube.com/watch?v=okEk7iKQccU',
    },
    {
      name: 'Why is Sony Launching Its Own Blockchain Platform?',
      url: 'https://technologymagazine.com/articles/why-is-sony-launching-its-own-blockchain-platform',
    },
    {
      name: 'Sony Blockchain Technology',
      url: 'https://www.japantimes.co.jp/business/2024/09/18/companies/sony-blockchain-technology/',
    },
    {
      name: 'Astar Network',
      url: 'https://astar.network/',
    },
    {
      name: 'Astar',
      url: 'https://coinmarketcap.com/currencies/astar/',
    },
    {
      name: 'Astar Coins',
      url: 'https://www.coingecko.com/en/coins/astar',
    },
  ],
  faucet: [
    {
      name: 'Development of Blockchain "Soneium™"',
      url: 'https://www.sony.com/en/SonyInfo/News/Press/202408/24-029E/',
    },
    {
      name: 'Soneium',
      url: 'https://www.coingecko.com/learn/what-is-soneium-sony-crypto#:~:text=Sony%20launched%20Soneium%2C%20a%20Layer,Optimism%2C%20joining%20the%20Superchain%20ecosystem.',
    },
    {
      name: 'Soneium token airdrop guide',
      url: 'https://boxmining.com/soneium-token-airdrop-guide/',
    },
    {
      name: 'The Sony Blockchain',
      url: 'https://www.youtube.com/watch?v=okEk7iKQccU',
    },
    {
      name: 'Why is Sony Launching Its Own Blockchain Platform?',
      url: 'https://technologymagazine.com/articles/why-is-sony-launching-its-own-blockchain-platform',
    },
    {
      name: 'Sony Blockchain Technology',
      url: 'https://www.japantimes.co.jp/business/2024/09/18/companies/sony-blockchain-technology/',
    },
    {
      name: 'Astar Network',
      url: 'https://astar.network/',
    },
    {
      name: 'Astar',
      url: 'https://coinmarketcap.com/currencies/astar/',
    },
    {
      name: 'Astar Coins',
      url: 'https://www.coingecko.com/en/coins/astar',
    },
  ],
}
